### ISSUE TITLE
dnscrypt-proxy wont start [FATAL] listen udp 127.0.0.1:65053: errno -9

### ISSUE THREAD

**Issue by mike-pt** [thuantran/dnscrypt-asuswrt-installer#26]
I just installed this in my AC-66U but can't seem to get dnscrypt to start

I get a fatal error:
`[FATAL] listen udp 127.0.0.1:65053: errno -9`

Changing the port makes no difference :/ Also tried to reinstall and still see the same... any idea why this would happen ?

**Comment by thuantran** [comment]
Check this issue https://github.com/jedisct1/dnscrypt-proxy/issues/118. Upstream binary does not work on MIPS router as the WARNING suggested during installation, I only left the option to install on MIPS so  some people who are working on it can use this script to test.

**Comment by mike-pt** [comment]
thanks

**Comment by dwimmer** [comment]
This is a golang bug https://github.com/golang/go/issues/23446. My patch to fix this was accepted, so this should be fixed in Go 1.11 (which should be out this month). Assuming dnscrypt-proxy updates to Go 1.11 when it is available everything should work fine on the mips routers then. (I'm using a self-built version on my RT-AC66U right now.)
