### ISSUE TITLE
Compatibility problem as PiHole resolver

### ISSUE THREAD

**Issue by labodj** [thuantran/dnscrypt-asuswrt-installer#332]
@thuantran  hi and thaks for your installer
I'm using Dnscrypt-proxy in my Asus router as DNS resolver for PiHole running on a Raspebrry Pi in the LAN.
Every device in my LAN should point to PiHole IP as its DNS server.

I achieve that the following way

1. DHCP options, DNS servers 1 & 2 set to PiHole IP
2. "Advertise router's IP in addition to user-specified DNS" disabled
3. WAN DNS1 to PiHole IP, WAN DNS2 blank
4. DNS filter set to PiHole IP for any device that ignores DHCP DNS (eg Google Home devices use hardcoded Google DNS servers)
5. DNS filter off for PiHole Device so it can resolve dns queries using dnscrypt proxy running on the Asus router.

This way PiHole shows me precise statistics for every "DHCP compliant" device with the minor inconvenience that any device that ignores DHCP DNS is showed as Router IP due to the fact that the query is redirected by DNS filter.

The problem is that your script resets DHCP DNS1, DHCP DNS2 and enables "Advertise router's IP in addition to user-specified DNS"
in [installer#L183-185 ](https://github.com/thuantran/dnscrypt-asuswrt-installer/blob/391a57e9eb964c4c6a64d560a93a5a60143312c2/installer#L183-L185)

I think this behavior should be optional, user selectable with an option during the installation process.

Do you think it can be possible?

For the moment I solved my issue commenting those lines and everything work as expected.

**Comment by jumpsmm7** [comment]
You are welcome to use whatever work around you would like, but the entries are enforced for users not attempting to do such configurations (a.k.a prevent user miss-configurations) that could otherwise break things for the non technically inclined. 
Might I ask why you simply don't run dnscrypt on your pihole device itself? It is rather easy to configure. (much like pihole is).

https://github.com/pi-hole/pi-hole/wiki/DNSCrypt-2.0

this prevents you having to point pihole back at the router for master-ship of DNS queries (a.k.a potential dns loops).

**Comment by jumpsmm7** [comment]
I didn't make it optional for those attempting to run stubby, but I did make it optional for you. Don't worry. I don't plan to maintain this script too much longer. I just hope DNScrypt-proxy 2 devs change too much drastically in the future that will make this script obsolete as a installing method. Best wishes.
