### ISSUE TITLE
Is it possible to add support for sending lan device info (Request) 

### ISSUE THREAD

**Issue by RouterCFW** [thuantran/dnscrypt-asuswrt-installer#347]
Is it possible to add support for an option to send device names from the router to the dns server so services like nextdns can see individual devices on the lan I know the nextdns cli can do this but it’s buggy

**Comment by jumpsmm7** [comment]
This is strictly on DNScrypt-Proxy devs in to-do. Let me fill you in on the full details, while we can send client information using DNSMASQ, to DNScrypt-procy, there are two layers of DNS being passed around, before it finally gets sent to NextDNS. DNSmasq can mark client traffic with arbitrary tracing elements, and it can also forward full subnet and mac information of individual clients, however, it would only send this to dnscrypt-proxy. The problem then comes to dnscrypt-proxy to forward this information dnsmasq sent to it. There is no telling if dnscrypt-proxy can even do such especially on a per client basis from a forwarded source. The only possible way to do such is if we skip dnsmasq for port 53 DNS, and make Dnscrypt-proxy the sole proprietor of DNS at port 53, obviously dnsmasq would still have to hand out IP address's to clients and dnscrypt-proxy would have to be setup with the proper reverse lookup information to be able to obtain hostnames of clients from dnsmasq. Still that would be a long shot, just to see if we could some how leverage Dnscrypt-proxies ECS client information sending capabilities so that each client interaction could be visible on next-dns.

**Comment by jumpsmm7** [comment]
The problem we run into is we would be fundamentally changing the installer script, to satisfy the use of a paid for service such as NextDNS. The script it self was not intended, by design, to not allow users to be able to use services like diversion. If this became the new default of the installer, we would effectively disenfranchise all users of Dnscrypt-proxy+diversion combinations. I don't see myself making that happen. And as a secondary feature, I don't see my self having enough time to implement and test this at the present time.

**Comment by jumpsmm7** [comment]
My suggestion is to use AdGuardHome instead of dnscrypt-proxy. There you can put your nextdns address for doh dot or plain dns as the upstream server. I already have AdGuardHome set up as the main DNS to clients as mentioned in the changes I would have to make to dnscrypt-proxy. In this case, all you would have to do is enable the ECS subnet capabilities of AdGuardHome. It would then forward your client data to your next dns account. 

https://github.com/jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer

**Comment by RouterCFW** [comment]
Oh okay thnx
