### ISSUE TITLE
dnscrypt-proxy failed to start

### ISSUE THREAD

**Issue by x86demon** [thuantran/dnscrypt-asuswrt-installer#39]
Hi. Thank you for installer that brings dnscrypt-proxy v2 to asuswrt routers.
I've installed dnscrypt-proxy with your installer script on ASUSWRT-Merlin RT-N66U 380.69-2
Getting error
```
[FATAL] listen udp 127.0.0.1:65053: errno -9
```

And is it possible to install it to entware partition instead of jffs?

**Comment by thuantran** [comment]
MIPS router does not work after the upgrade to v2 due to upstream support is not compatible with the old kernel used on these routers. I keep the support in the script as some devs were trying to fix it, but there's no fix yet, likely won't, so don't hold your breath on it.

If it's that way still for a few more version of dnscrypt-proxy, I'll remove support for MIPS router completely in my script, sorry.

**Comment by thuantran** [comment]
MIPS router does not work after the upgrade to v2 due to upstream support is not compatible with the old kernel used on these routers. I keep the support in the script as some devs were trying to fix it, but there's no fix yet, likely won't, so don't hold your breath on it.

If it's that way still for a few more version of dnscrypt-proxy, I'll remove support for MIPS router completely in my script, sorry.
